[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[terminal]
shell = "fish"

[window]
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12

