[[dir]]
source = "alacritty"
target = "~/.config/alacritty"
exact = true

[[dir]]
source = "bat"
target = "~/.config/bat"
exact = true

[[dir]]
source = "cargo"
target = "~/.cargo"
exact = false

[[dir]]
source = "fish"
target = "~/.config/fish"
exact = false

[[file]]
source = "git/.gitconfig"
target = "~/.gitconfig"

[[file]]
source = "starship/starship.toml"
target = "~/.config/starship.toml"

[[dir]]
source = "tmux"
target = "~/.config/tmux"

[[dir]]
source = "ghostty"
target = "~/.config/ghostty"
exact = true

[[dir]]
source = "helix"
target = "~/.config/helix"
exact = true

[[file]]
source = "mpv/mpv.conf"
target = "~/.config/mpv/mpv.conf"
