theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[keys.normal]
"0" = "goto_line_start"
"$" = "goto_line_end"
